//! What the proxy records about one model call (feature 03): the body of an
//! `llm.call` event, and the `calls.list` wire types that return it.
//!
//! Metadata only. Content (request and response bodies) is stored separately by
//! address, and only while capture is on. Every number is an integer, so the
//! record can go on the hash path (feature 02, "No floats on the hash path").
//! Credentials never appear here: headers are recorded from an allowlist.

use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

/// Event kind of a recorded model call.
pub const LLM_CALL_KIND: &str = "llm.call";

/// How a proxied call ended.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS), ts(export))]
#[serde(rename_all = "camelCase")]
pub enum CallOutcome {
    /// The upstream answered with a status below 400 (2xx, or a 3xx passed
    /// through to the client) and the body ended normally, with no `error`
    /// event in a stream.
    Completed,
    /// The upstream answered with a status of 400 or more, or a stream carried
    /// an `error` event.
    UpstreamError,
    /// The client went away before the response ended. If it left before the
    /// response head, the record's `status` is 0.
    ClientCancelled,
    /// The proxy could not reach the upstream (connect error or timeout); the
    /// client got the proxy's own 502 or 504.
    UpstreamUnreachable,
    /// The upstream's body ended with an error part-way (connection reset).
    Incomplete,
}

/// Token counts as the provider reported them. Never estimated.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS), ts(export))]
#[serde(rename_all = "camelCase")]
pub struct Usage {
    #[cfg_attr(test, ts(type = "number"))]
    pub input_tokens: u64,
    #[cfg_attr(test, ts(type = "number"))]
    pub output_tokens: u64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[cfg_attr(test, ts(type = "number | null", optional))]
    pub cache_creation_input_tokens: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[cfg_attr(test, ts(type = "number | null", optional))]
    pub cache_read_input_tokens: Option<u64>,
}

/// The body of an `llm.call` event.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS), ts(export))]
#[serde(rename_all = "camelCase")]
pub struct LlmCallRecord {
    /// `anthropic` in feature 03.
    pub provider: String,
    pub method: String,
    /// The request path without its query, such as `/v1/messages`.
    pub path: String,
    /// The status the client received (the upstream's, or the proxy's own);
    /// 0 when the client got no response (it left before the response head).
    pub status: u16,
    pub outcome: CallOutcome,
    /// The response was `text/event-stream`.
    pub streamed: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[cfg_attr(test, ts(optional))]
    pub model: Option<String>,
    /// The upstream's `request-id` header.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[cfg_attr(test, ts(optional))]
    pub request_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[cfg_attr(test, ts(optional))]
    pub stop_reason: Option<String>,
    /// `error.type` from an error body or a stream's `error` event.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[cfg_attr(test, ts(optional))]
    pub error_type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[cfg_attr(test, ts(optional))]
    pub usage: Option<Usage>,
    /// When the proxy received the request, in Unix milliseconds.
    #[cfg_attr(test, ts(type = "number"))]
    pub started_at_ms: u64,
    /// Milliseconds until the upstream's response headers arrived.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[cfg_attr(test, ts(type = "number | null", optional))]
    pub ttfb_ms: Option<u64>,
    /// Milliseconds until the response body ended (or the call was abandoned).
    #[cfg_attr(test, ts(type = "number"))]
    pub duration_ms: u64,
    #[cfg_attr(test, ts(type = "number"))]
    pub request_bytes: u64,
    #[cfg_attr(test, ts(type = "number"))]
    pub response_bytes: u64,
    /// Raw values of `request-id`, `retry-after`, `x-should-retry` and every
    /// `anthropic-ratelimit-*` response header, by lower-case name.
    pub rate_limit_headers: BTreeMap<String, String>,
    /// W3C trace id (32 lower-case hex): the client's `traceparent`, or one
    /// generated by the proxy when the request had none (not forwarded).
    pub trace_id: String,
    /// The client's `User-Agent`, at most 200 bytes.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[cfg_attr(test, ts(optional))]
    pub user_agent: Option<String>,
    /// Capture was on but none of the bodies were stored: they were over the
    /// store's content cap, or the content key couldn't be loaded (a locked
    /// keychain, say).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[cfg_attr(test, ts(optional))]
    pub content_truncated: Option<bool>,
}

/// Params of `calls.list`. Given by name; unknown members are refused.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS), ts(export))]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct CallsListParams {
    /// 1 to 200; 50 when absent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[cfg_attr(test, ts(optional))]
    pub limit: Option<u32>,
    /// Only calls recorded before this global position (the previous page's
    /// `nextBefore`); the newest calls when absent.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[cfg_attr(test, ts(type = "number | null", optional))]
    pub before: Option<u64>,
}

/// One recorded call in a `calls.list` result.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS), ts(export))]
#[serde(rename_all = "camelCase")]
pub struct CallEntry {
    #[cfg_attr(test, ts(type = "number"))]
    pub global_pos: u64,
    pub run_id: String,
    pub call: LlmCallRecord,
}

/// Result of `calls.list`: newest first.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(test, derive(ts_rs::TS), ts(export))]
#[serde(rename_all = "camelCase")]
pub struct CallsListResult {
    pub calls: Vec<CallEntry>,
    /// Pass as `before` for the next (older) page; absent on the last page.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[cfg_attr(test, ts(type = "number | null", optional))]
    pub next_before: Option<u64>,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn record() -> LlmCallRecord {
        LlmCallRecord {
            provider: "anthropic".into(),
            method: "POST".into(),
            path: "/v1/messages".into(),
            status: 200,
            outcome: CallOutcome::Completed,
            streamed: true,
            model: Some("claude-opus-5".into()),
            request_id: None,
            stop_reason: Some("end_turn".into()),
            error_type: None,
            usage: Some(Usage {
                input_tokens: 10,
                output_tokens: 20,
                cache_creation_input_tokens: None,
                cache_read_input_tokens: Some(5),
            }),
            started_at_ms: 1_790_000_000_000,
            ttfb_ms: Some(120),
            duration_ms: 900,
            request_bytes: 512,
            response_bytes: 2048,
            rate_limit_headers: BTreeMap::new(),
            trace_id: "0af7651916cd43dd8448eb211c80319c".into(),
            user_agent: None,
            content_truncated: None,
        }
    }

    #[test]
    fn a_record_is_camel_case_and_has_no_floats() {
        let value = serde_json::to_value(record()).unwrap();
        assert_eq!(value["usage"]["cacheReadInputTokens"], 5);
        assert!(
            value.get("requestId").is_none(),
            "absent options are omitted"
        );
        crate::event::check_body_numbers(&value).unwrap();
    }

    #[test]
    fn calls_list_params_refuse_unknown_members() {
        assert!(serde_json::from_str::<CallsListParams>(r#"{"limit":5,"x":1}"#).is_err());
        let params: CallsListParams = serde_json::from_str("{}").unwrap();
        assert_eq!(params, CallsListParams::default());
    }
}
